In [44]:
import numpy as np
x = np.arange(9).reshape((3,3))
y = np.copy(x)
z = np.copy(x)

state = np.array([x, y, z])
state[0, 1, 2]

# state[:,1:,:]
np.concatenate((state[:,1:,:], np.zeros((3,1,3), dtype=int)), out=state, axis=1)
np.concatenate((state[:,1:,:], np.zeros((3,1,3), dtype=int)), out=state, axis=1)
indice = np.max(np.where(state != 0), axis=1)
print(indice)
state[tuple(indice)] = -1
state

[2 0 2]


array([[[ 6,  7,  8],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 6,  7,  8],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 6,  7, -1],
        [ 0,  0,  0],
        [ 0,  0,  0]]])

In [49]:
import numpy as np
x = np.arange(9).reshape((3,3))
y = np.copy(x)
z = np.copy(x)

state = np.array([x, y, z])
state = np.array([[[6, 7, 8],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[6, 7, 8],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[6, 7, 8],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

print("duration",np.max(np.where(state != 0), axis=1)[1])


duration 0


array([0, 6, 7, 8])

In [4]:
import numpy as np
np.testing.assert_allclose(np.full((1,3,42), -2, dtype=int), -2)

In [7]:
from random import randrange
mydict = {}
for i in range(3, 9):
    mydict[i] = randrange(1, 10)
mydict

{3: 8, 4: 6, 5: 7, 6: 2, 7: 1, 8: 2}

In [18]:
import numpy as np

num_resource_type = 2
num_job_slot = 5
# num_job_slot = 3
time_size = 5
resource_size = 3
shape = (
    num_job_slot,
    num_resource_type,
    time_size,
    resource_size,
)
sample_arr = [True, False]
bool_arr = np.random.choice(sample_arr, size=shape)
bool_arr

array([[[[ True,  True, False],
         [ True, False,  True],
         [ True, False,  True],
         [False, False,  True],
         [False,  True,  True]],

        [[False, False,  True],
         [ True,  True,  True],
         [False,  True,  True],
         [False, False, False],
         [False,  True, False]]],


       [[[False, False,  True],
         [False,  True, False],
         [ True,  True,  True],
         [False, False,  True],
         [False, False, False]],

        [[False, False,  True],
         [ True, False, False],
         [ True, False,  True],
         [ True,  True, False],
         [ True, False, False]]],


       [[[ True, False, False],
         [False, False,  True],
         [ True, False,  True],
         [ True,  True, False],
         [False, False,  True]],

        [[ True,  True,  True],
         [ True, False,  True],
         [ True,  True,  True],
         [False, False,  True],
         [False, False, False]]],


       [[[False, False

In [11]:
x = np.array([1,2,3])
y = np.array([4,5,6])

np.concatenate((x, y))


array([1, 2, 3, 4, 5, 6])

In [2]:
from res_mgmt.envs.res_mgmt_env import ResMgmtEnv

env = ResMgmtEnv()
obs = env.reset()

action = env.action_space.sample()
print(action)
obs, reward, done, info = env.step(action)
print(obs, reward, done, info)

ModuleNotFoundError: No module named 'res_mgmt'